### ISSUE TITLE
Features Request

### ISSUE THREAD

**Issue by deep1931** [Sorbh/ticketviewflutter#1]
Hello,

Thanks for the very nice plugin.

I have found some issue which I do not know acutally are issue or I am doing something wrong while implementation . 

1. We use Verticle Axis that time, the case is, **triangleAxis:Axis.vertical** and **drawBorder:false** then whole design get disturbed. Then i set borderRadius to a 200 or 300 or any high value then we can get arcless border.
2. We can set corner radius of ticket when **drawBorder:false**, cornerRadius property set radius of background not ticket,

`drawArc: true,
triangleSize: const Size(20, 10),
dividerColor: mainRed,
dividerStrokeWidth: 1,
borderRadius: 300,
drawBorder: true,
corderRadius: 10,
triangleAxis: Axis.vertical,
trianglePos: .7,`

Please look into it..

Regards

**Comment by jxstxn1** [comment]
Can you please provide more informations, I will take a look and create a Pull Request.
Please sort your  Problem in those 3 section:
- What you did(with code example for reconstruction)
- What did you expected(if possible Screenshot)
- What happened instead (if possible Screenshot)
